version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: senha123
      POSTGRES_USER: dev
      POSTGRES_DB: task-manager
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'