version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: senha123
      POSTGRES_USER: dev
      POSTGRES_MULTIPLE_DATABASES: task_manager,task_manager_test
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'